### ISSUE TITLE
Nit: the integers are not a field.

### ISSUE THREAD

**Issue by aegolden** [WesleyAC/blog#18]
Your ECC for beginners post implies that Z is a field, but this is not correct. Integers mostly do not have multiplicative inverse’s in Z.

**Comment by aegolden** [comment]
s/inverse’s/inverses (autocorrect :P)

**Comment by WesleyAC** [comment]
Should be fixed by 65acb5e5f84fdbd3778c552475c1fe94b1eda606 :+1:
