### ISSUE TITLE
Typo: Double "to"'s

### ISSUE THREAD

**Issue by derekmhewitt** [WesleyAC/blog#19]
In this paragraph:

If you see evaluating the candidate's ability to to the job as the ideal for an interview, this also reveals many of the things that are wrong with tech interviews at the moment - I've never had an interview that tried to evaluate my ability to work in a team or prioritize tasks - both of which are probably more important to doing well in a software engineering job than being able to find anagrams in O(n) time.

You have two "to"'s in the first line.  It's probably supposed to be "to do".

**Comment by WesleyAC** [comment]
Thanks for catching that! Fixed in 01720e8.
