### ISSUE TITLE
Bluesky post corrections

### ISSUE THREAD

**Issue by snarfed** [WesleyAC/blog#27]
Hi! This is a fun way to post blog comments. Re https://blog.wesleyac.com/posts/bluesky , a few corrections:

* You're right that the web and mobile apps are currently closed source, but the server is open source, https://github.com/bluesky-social/atproto , with related backend code in a few other public repos like https://github.com/bluesky-social/did-method-plc . I think they hope to switch their PDS to be run by indigo eventually, but not in the near term.
* It's maybe semantics, but their funding isn't really VC style. Twitter took no equity stake in exchange for their $13M funding, so it's more like a grant.
* The company itself is a PBLLC, which is meaningfully different from a traditional private C-corp, and they've disclosed their governance structure. The board is three people - Jay, Jack, Jeremie Miller - each with 1/3 vote.

More details and citations: https://snarfed.org/bluesky-corporate-ownership-and-structure

**Comment by WesleyAC** [comment]
Thanks for the corrections.

* The PDS part of the server is public, but it looks like the web client (`staging.bsky.app`) part of it is proprietary — is that correct?
* I don't think it's public who has equity in Bluesky, although Twitter as a company did say they don't have any. Characterizing it as a "grant" is funny when Jack Dorsey, who approved the funding, is ⅓ of the board.
* Do you have a link to where they "disclosed their governance structure"? Depending on who the shareholders are (which is nonpublic, AFAICT), the makeup of the board is not terribly important. That being said, three people controlling the protocol with no public input is not really meaningfully "decentralized"

**Comment by snarfed** [comment]
> The PDS part of the server is public, but it looks like the web client (`staging.bsky.app`) part of it is proprietary — is that correct?

Right, at least so far.

> I don't think it's public who has equity in Bluesky, although Twitter as a company did say they don't have any. Characterizing it as a "grant" is funny when Jack Dorsey, who approved the funding, is ⅓ of the board.

Fair. The key point is that Twitter/Jack took no equity, which is the main point of traditional investing. We don't have to call it a grant, but it's definitely closer to philanthropic funding, where often large ongoing donors do take board seats (or directorships etc) and/or attach strings to their donations, but don't take "equity" in the org itself.

> Do you have a link to where they "disclosed their governance structure"? Depending on who the shareholders are (which is nonpublic, AFAICT), the makeup of the board is not terribly important. That being said, three people controlling the protocol with no public input is not really meaningfully "decentralized"

Yup, citations are all in the linked post, https://snarfed.org/bluesky-corporate-ownership-and-structure . They haven't published their literal cap table, and I wouldn't expect them to, but [they did say](https://twitter.com/bluesky/status/1518707603232083968) _The company is owned by the team itself, without any controlling stake held by Twitter,_ and [more recently](https://blue.amazingca.dev/?username=jay.bsky.team&postid=3ju65fvwo6h2q) _twitter holds no stake_.

Standards bodies and related governance structures are obviously hugely important, but often more useful further down the road than at the beginning. Protocols etc often start out elsewhere, iterate and evolve quickly, and then get formalized once they've proven themselves. Pave the cowpaths, design by committee (in the negative), rough consensus and running code, etc. Even ActivityPub itself started as a single person's thing, Evan Prodromou's pump.io.

**Comment by WesleyAC** [comment]
> The key point is that Twitter/Jack took no equity

Where are you getting that Jack took no equity from? I've seen that *Twitter* took no equity, but Twitter ≠ Jack.

> They haven't published their literal cap table, and I wouldn't expect them to

See, but the cap table is the thing that actually determines who has power, so it seems really strange to say that they're public about their governance structure because the board appointments are public, when it's the shareholders who get to decide who the board is and can fire them if they don't like the decisions.

Of course, even if they did publish this, they don't seem to have any plans for community governance of the protocol. They've had like four years to think about this stuff, it's very strange that they've been (publicly) silent about it.

I think you're not really correct on the history of ActivityPub — it came out of OStatus, which itself was a stitching together of existing open protocols, and was developed by a team of people working under the W3C process, not just Evan Prodromou.

**Comment by snarfed** [comment]
Sounds like we're coming to different conclusions from mostly shared facts. Which is ok! I just wanted to raise the few factual corrections. I'm more optimistic than you are, but I'm glad people have different takes. Time will tell!

> Where are you getting that Jack took no equity from? I've seen that _Twitter_ took no equity, but Twitter ≠ Jack.

Twitter made the investment, not Jack. And again, they've said explicitly that the company is owned by the team itself. Lots more in https://snarfed.org/bluesky-corporate-ownership-and-structure , including citations.

Also they're a PBLLC, so their corporate governance itself works a bit different than standard C-corp shareholder/board.

If you want to assume bad faith or hidden agendas or internal machinations, you can, but they've been far more public about all of this and the concrete steps they're taking to be different than most startups. Which you're right that they damn well should, given their goals! The signs so far don't tell me "they're putting one over on us," as much as "it's a good start, and it's early."

> Of course, even if they did publish this, they don't seem to have any plans for community governance of the protocol. They've had like four years to think about this stuff, it's very strange that they've been (publicly) silent about it.

Agreed, community/standards body governance down the road will definitely be important!

(Jay was hired in mid 2021, then spent around half a year negotiating for Bluesky to be a separate entity from Twitter. That finally happened at the end of 2021. https://blueskyweb.xyz/blog/2-28-2022-how-it-started ("Phase 2"). Much of the protocol design has been a team effort since then. So, maybe a year and a half to two years.)

> I think you're not really correct on the history of ActivityPub — it came out of OStatus, which itself was a stitching together of existing open protocols, and was developed by a team of people working under the W3C process, not just Evan Prodromou.

OStatus, yes, good point! Both are true. I've been involved in the space for decades, I know the history and many of the people well, including even earlier predecessors like OpenSocial and Atom. ActivityPub's spiritual predecessor was OStatus, true, which Evan was very involved in too. He then prototyped pump.io and ActivityPump, took it to the W3C, and a number of other key people ran with it and standardized it as ActivityPub. https://en.wikipedia.org/wiki/ActivityPub , https://en.wikipedia.org/wiki/OStatus#Standards_work

**Comment by WesleyAC** [comment]
> Twitter made the investment, not Jack

Right, I understand this. However, Jack does seem to be involved, and his involvement is not clear. I believe that when Twitter made the $13M investment, Jack didn't have any equity, but it's not clear to me that's still the case now.

> the company is owned by the team itself

Who "the team" is is pretty nebulous, as far as I can tell.

> Also they're a PBLLC, so their corporate governance itself works a bit different than standard C-corp shareholder/board.

It's been several years since I looked at the laws around this (and I haven't looked at which state they're registered in), but my impression of B-corps is that the entire thing is largely toothless ethicswashing that does nothing to change structural problems inherent to private corporations. I guess you got a different impression.

> Sounds like we're coming to different conclusions from mostly shared facts.

Yeah, this seems about right. To be clear, I don't think Bluesky is *malicious*, I just think that they are building in a way that will lead to a system that is fundamentally centralized from a perspective of who holds power over the ecosystem. That seems more the fault of silicon valley brainworms than malice.

**Comment by snarfed** [comment]
> Right, I understand this. However, Jack does seem to be involved, and his involvement is not clear. I believe that when Twitter made the $13M investment, Jack didn't have any equity, but it's not clear to me that's still the case now...Who "the team" is is pretty nebulous, as far as I can tell.

Jay has been clear in these conversations and others that when she says "the team," she means the full time employees, not Jack or Jeremie or others.

> Yeah, this seems about right. To be clear, I don't think Bluesky is _malicious_, I just think that they are building in a way that will lead to a system that is fundamentally centralized from a perspective of who holds power over the ecosystem. That seems more the fault of silicon valley brainworms than malice.

Definitely understood. This is probably the crux of our disagreement. Based on what we know so far of Bluesky and the environment around it, will it be "default decentralized" (or "default good" or whatever), in the PG "default alive" sense, or not. We'll see!
